### ISSUE TITLE
Project Form: Update Currency Field

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/NGO-admin#11]
On the project form:

- Change existing currency type field from plain text field to drop-down field.
- Convert project budget into USD using exchange rate from a specified date.

**Comment by RBFraxinus** [comment]
Currency options for the dropdown may be found on the IATI standard website.  This is a link to v2.02.  http://iatistandard.org/202/codelists/Currency/   You may access the list in csv, xml, or json there.

**Comment by mzlock** [comment]
I added the drop-down.  @brianjlandau should be able to fill in the currencies from here.
