### ISSUE TITLE
Project Form: Add Related Content

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/NGO-admin#12]
On the project form:

- Add ability to add file URLS to projects (plain text field). Each URL would link to an external file.

**Comment by mzlock** [comment]
@lsweltz - were you envisioning this as a repeater field?

**Comment by mzlock** [comment]
Trying this out:  Added a new field to where media is uploaded/added.

It's not a fancy JS repeater field - it saves and refreshes the page and shows the added photo.

![screen shot 2016-08-26 at 6 15 30 pm](https://cloud.githubusercontent.com/assets/1087001/18021986/44bb7cbc-6bb9-11e6-888f-165339b31005.png)

**Comment by lsweltz** [comment]
- Display both Choose File field and Enter an Image URL field in a single "Add a New Image" box. Both can be displayed at once.

**Comment by mzlock** [comment]
@lsweltz - edited the layout for this a bit:

![screen shot 2016-09-09 at 1 09 35 pm](https://cloud.githubusercontent.com/assets/1087001/18395884/b30f8228-768e-11e6-99a7-fbd3c9a3641e.png)

**Comment by lsweltz** [comment]
Can we add more vertical space between the two options and potentially add "OR" between them as well?

**Comment by mzlock** [comment]
@lsweltz - better ?

![screen shot 2016-09-09 at 2 30 42 pm](https://cloud.githubusercontent.com/assets/1087001/18398273/08cc82be-769a-11e6-9996-d41000caa537.png)

**Comment by lsweltz** [comment]
@mzlock I actually meant between the two image options (upload and URL). Does that make sense? Sorry for the confusion!

**Comment by mzlock** [comment]
OOooooooooh.  Haha.  Ok, will add.

**Comment by mzlock** [comment]
![screen shot 2016-09-09 at 3 01 23 pm](https://cloud.githubusercontent.com/assets/1087001/18399323/4f425ed6-769e-11e6-8aab-c10884b68fd9.png)

**Comment by lsweltz** [comment]
@mzlock 👍

**Comment by mzlock** [comment]
done and ready for @brianjlandau then
