### ISSUE TITLE
Organization Form: Add Related Content

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/NGO-admin#13]
On the organization form:

- Add ability to upload image files to organizations (file upload field).
- Add ability to add Vimeo or YouTube URL to organizations (plain text field).

**Comment by mzlock** [comment]
There is a Media tab for organizations, it was just removed and being hidden for some reason.  All I did for this Issue was un-hide that tab.

Follow Issue #12 for actual changes to that form.
