### ISSUE TITLE
Update dashboard

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/NGO-admin#18]
@mzlock 

Based on [this screenshot](https://files.slack.com/files-pri/T024F9JB8-F25EJQ6G3/screencapture-localhost-3000-1472246282374.png):

- What do you think about underlining the links? They seem hard to see.
- Are there any easy visual wins for the "Your Projects" stats? One Idea: Move number above description text and make description text larger (one word per line).
- Change "Your Projects Ending Soon" to "Projects Ending Soon"
- For the Your Active Projects and Your Closed Projects sections, add a "View Projects" link in the upper right

**Comment by mzlock** [comment]
@lsweltz 

1. Will do
2. Not sure what to do with that - currently re-using a style
3. Will do
4. Both instances of "View Projects" should just go to `/admin/projects`, right?

**Comment by mzlock** [comment]
Current status of the dashboard after those couple of changes:
![screencapture-localhost-3000-admin-1473186516971](https://cloud.githubusercontent.com/assets/1087001/18285883/602d968c-743e-11e6-9425-d02a9f24ccce.png)

**Comment by lsweltz** [comment]
Yeah, the filtered list would be preferable, if possible. If it is, move forward with that and use the language "View All Active Projects" and "View All Closed Projects".

**Comment by mzlock** [comment]
Re: Active/Closed project links - Done!

**Comment by lsweltz** [comment]
Additional updates from InterAction:

- Add project totals to the country list like the sector list
Needs clarification. The project total is already listed by the countries list. 

- Project list should be collapsible in expiration list – can we revise the time frames to avoid repletion in each group, e.g. “Projects ending within 1 month”, “Projects ending in 2 – 6 months”, and “Projects ending in 7 – 12 months” 
- Are the countries going to be columned? Should we make that collapsible as well? Show 20 countries or so and then do a show more list?
- Unused sectors should be visible, but there should be a very distinguished difference between those that they have projects under and those they do not
- Active sectors should be listed in descending order (highest first) and then inactive sectors should be alphabetical
- All country and sector hyperlinks for active projects should show only the organization’s projects on that page vs. total projects in that sector or country
- Include front end organization contact information (media, data, and overall) on the first segment to ensure that it remains updated
- Can we make the bottom section include both active and total projects for comparison – titles should be # of projects, # of reporting organizations, and # of countries.
- Add a header to the last section to make it clear that this is site-wide data.
- On the completed section page: need to remove “View All Closed Projects” at the top. Should probably also remove the links to countries and partners/donors. I don’t think closed version views of these exist.
- Remove the donors and partners lists for now as appropriate pages do not exist for all of these links.

**Comment by lsweltz** [comment]
Additional updates from InterAction:

- [ ] Add project totals to the country list like the sector list (show number of projects for each individual country)

- [ ] Project list should be collapsible in expiration list – can we revise the time frames to avoid repletion in each group, e.g. “Projects ending within 1 month”, “Projects ending in 2 – 6 months”, and “Projects ending in 7 – 12 months” 

- [ ] Are the countries going to be columned? Should we make that collapsible as well? Show 20 countries or so and then do a show more list?
- Use same approach as sectors for the columns 
- Only show countries that have projects
- If there are more than 20 countries, collapse the list.
- Display countries in order by number of projects (alphabetical if tied)

- [ ] Unused sectors should be visible, but there should be a very distinguished difference between those that they have projects under and those they do not
- Reverse out the circles for sectors that have projects (blue circle with white text) 
- Lighten the text to a gray for sectors that don't have projects

- [ ] Active sectors should be listed in descending order (highest first) and then inactive sectors should be alphabetical

- [ ] All country and sector hyperlinks for active projects should show only the organization’s projects on that page vs. total projects in that sector or country
- Instead of linking "Afghanistan" to the public page of all projects in Afghanistan, link to a filtered list of the org's project in Afghanistan (admin)

- [ ] Can we make the bottom section include both active and total projects for comparison – titles should be # of projects, # of reporting organizations, and # of countries.
- Kill the 3 box design
- Reuse style from other boxes on the page

- [ ] Add a header to the last section to make it clear that this is site-wide data.

- [ ] On the completed section page: need to remove “View All Closed Projects” at the top. Should probably also remove the links to countries and partners/donors. I don’t think closed version views of these exist.

- [ ] Remove the donors and partners lists for now as appropriate pages do not exist for all of these links.
- Unlink these items

**Comment by mzlock** [comment]
I tackled the list above.  Here is the new screenshot of the dashboard:

![screencapture-localhost-3000-admin-1473459510280](https://cloud.githubusercontent.com/assets/1087001/18404658/e3e99cf0-76b9-11e6-9a69-424ee09267ca.png)
