### ISSUE TITLE
Project Form: Add the ability to add file resources 

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/NGO-admin#23]
- Add ability to add file URLS to projects (plain text field). 
- Each URL would link to an external file.
- Uses the same functionality as the resources tab on the organization form.

**Comment by mzlock** [comment]
Apparently this page and form already existed and works.  At one point or another, someone just hid that page from the Project form sidebar

![screen shot 2016-10-07 at 5 16 07 pm](https://cloud.githubusercontent.com/assets/1087001/19205672/e990756c-8cb1-11e6-9621-4dd3683e0dca.png)

@brianjlandau might want to have a look over this, in case there was a reason it was taken out?

**Comment by lsweltz** [comment]
👍
