### ISSUE TITLE
Project Form: Combine partners fields into a single dropdown

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/NGO-admin#24]
- Combine International Partners and Local Partners fields into a single Partners field
- [Screenshot](https://www.dropbox.com/s/s795tgvg5pfu161/Screenshot%202016-09-26%2015.07.27.png?dl=0)

**Comment by mzlock** [comment]
I eliminated the International Partners field and updated the labels on the Local Partners field so it could act as the one Partners field.

Passing to @brianjlandau to make an necessary back-end updates.

**Comment by lsweltz** [comment]
👍
