### ISSUE TITLE
Dashboard: Remove unnecessary space in project numbers 

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/NGO-admin#29]
URL: http://office.ngoaidmap.staging.vigetx.com/admin/
- For numbers with more than one digit, there is a space between the first and second digits
- [Screenshot](https://www.dropbox.com/s/e0y7joz99q0oxf2/Screenshot%202016-09-26%2016.01.31.png?dl=0)

**Comment by mzlock** [comment]
Assigned @brianjlandau since the extra spaces are being spat out by the back-end - they're not in the template.

**Comment by lsweltz** [comment]
👍
