### ISSUE TITLE
[User Password Reset] DEV: Users unable to reset their passwords.

### ISSUE THREAD

**Issue by brianjlandau** [InterActionNGO/NGO-admin#33]
[User Password Reset] Users are unable to reset their passwords. The password reset email's reset link is not working properly. The link display text is correct, but the link target is not, so when people click the link they get an error page.

**Comment by brianjlandau** [comment]
I couldn't see this, but I added some escaping to the output so hopefully it works now even if there's odd characters. @RBFraxinus if you could confirm that would be helpful.

**Comment by RBFraxinus** [comment]
sorry for the miscommunication on this -- i fixed this a few days ago and is working on production.  No need for the extra escapes.

**Comment by btornes** [comment]
:+1:
