### ISSUE TITLE
[Organization Form] FED: Budget not displaying correctly

### ISSUE THREAD

**Issue by brianjlandau** [InterActionNGO/NGO-admin#35]
[Backend - Organization Form] The budget field is truncating values when supplied with commas. "5,000,000" gets saved as "5". Can you make this field handle commas correctly, as the budget field in the projects form does?

**Comment by mzlock** [comment]
@brianjlandau - I took a look at this and it seems to be more back-end to me?  The field accepts "5000000" correctly, but turns "5,000,000" into "5" after the form submits and the page reloads.

**Comment by btornes** [comment]
@brianjlandau Looks good, but I can't close it!
