### ISSUE TITLE
[Dashboard] DEV: Headings don't seem to pull in correct numbers

### ISSUE THREAD

**Issue by brianjlandau** [InterActionNGO/NGO-admin#36]
[Backend - Member dashboard] Looks like the headings for the "Projects ending in ## months" section are not correct. In the member dashboard I viewed, there were two sections, both saying "# projects ending in 3 months", but one had projects ending in 3 months, and the other looked like it should've been labeled 12

**Comment by mzlock** [comment]
@brianjlandau - I can handle this one really quick, since it's a templating issue.

**Comment by btornes** [comment]
@mzlock @brianjlandau This looks great to me! (I can't close it)
