### ISSUE TITLE
[Project Form] DEV: Within the admin, forms take too long to load.

### ISSUE THREAD

**Issue by brianjlandau** [InterActionNGO/NGO-admin#37]
[Backend - Project Form] The project forms take a lot longer to load lately and we'd like to pinpoint what the cause is and address it soon if possible. Our first suspicion is possibly the thousands of organizations that are being loaded into the select elements for partners and prime awardees. Your thoughts?

**Comment by brianjlandau** [comment]
This will probably require a tool like NewRelic. I added a gem called bullet that looks for some potential slowdowns do to less performant SQL queries. It helped identify a few slow downs, but nothing huge and nothing on the form pages. So, there's not much we can do at this point.

**Comment by RBFraxinus** [comment]
I committed a temp fix for this a week or so ago, but I agree we should look into doing some query optimization, which I see you already gotten started on!
