### ISSUE TITLE
[DEV] Update Errors When Creating a Project

### ISSUE THREAD

**Issue by btornes** [InterActionNGO/NGO-admin#39]
From Robert:

Hello,
We're getting isolated emails from members who are getting errors pages when trying to manage their data.  One such example is from the user rwarwick@cwsglobal.org, who wrote that he can update projects ok, but gets a 500 server error page when he tries to create a new project.
I've been able to create projects successfully with super admin and even via my example regular admin account, so there' something distinct about his case.

**Comment by btornes** [comment]
Additional Info:

I just went in and logged in as one of Church World Service's old users (old.jknapp@cwsglobal.org) and attempted creating a project and got the "We're sorry but the page could not be loaded" useless error page.   

I did this around 8:40-8:42am EST if that helps you sort through the logs.

**Comment by brianjlandau** [comment]
Steps to reproduce: https://viget.slack.com/archives/D04VAPM0L/p1482353455000038

**Comment by btornes** [comment]
:+1:
