### ISSUE TITLE
Organization Form: Update Fields

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/NGO-admin#5]
On organization form:

Update fields to reflect [this spreadsheet](https://docs.google.com/spreadsheets/d/1pQEtjDNGRjegcq3lz9OeDN0HPYN-3LsaiDeIiawQh98/edit#gid=600925772).

**Comment by mzlock** [comment]
@lsweltz here are the changes to the organization form, as screenshots.

The data fields I may have to take another pass at after @brianjlandau integrates, since date fields are easier to do after the data exists.

Admin User form:

**Comment by brianjlandau** [comment]
I think this is done. I'm unaware of any changes that need to be made @lsweltz do you mind confirming this?

**Comment by lsweltz** [comment]
👍
