### ISSUE TITLE
Project Form: Add Helper Copy

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/NGO-admin#7]
- Add helper copy that provides a link to a form where members can submit an organization that does not appear in the drop-down field. The same helper copy should also be included with the donor and prime awardee fields.

**Comment by mzlock** [comment]
Use this google form link:
https://docs.google.com/forms/d/1mfdojTnIm8XNDVt9UcyjY23hcpeOFQW5ZN0zCFejQAY/edit?usp=sharing

**Comment by mzlock** [comment]
@lsweltz - which fields should this helper text be associated with?  The Partner fields?

**Comment by lsweltz** [comment]
The helper copy should be included on the partner, donor, and prime awardee fields.

Copy:
If the organization is not listed here, you should complete and submit the new organization request form. You can access the form at http://bit.ly/2cpDqAk.

**Comment by mzlock** [comment]
@lsweltz - How does this look?

![screen shot 2016-09-09 at 2 43 18 pm](https://cloud.githubusercontent.com/assets/1087001/18398927/ce1e926c-769c-11e6-8043-3423ec83992a.png)
![screen shot 2016-09-09 at 2 50 13 pm](https://cloud.githubusercontent.com/assets/1087001/18398928/ce303170-769c-11e6-99e2-6135866332f6.png)

**Comment by lsweltz** [comment]
@mzlock 👍

**Comment by mzlock** [comment]
Cool.  This should be all set for @brianjlandau  then.

**Comment by lsweltz** [comment]
👍

**Comment by lsweltz** [comment]
@mzlock The amount field and the button extend beyond the green box in Chrome. Do you see that same issue? [Screenshot](https://www.dropbox.com/s/e8yrdwf6ffn6bgq/Screenshot%202016-10-13%2014.23.17.png?dl=0)

**Comment by brianjlandau** [comment]
@lsweltz is this good to go? @mzlock is there something I need to do on this?

**Comment by lsweltz** [comment]
Note: This design issue above still needs to be addressed.

**Comment by lsweltz** [comment]
@mzlock The update looks good. :+1:

When I add a donor, the donation amount appears twice. Is it possibly to remove the second instance? cc: @mzlock @brianjlandau 

![screenshot 2016-11-16 14 11 27](https://cloud.githubusercontent.com/assets/871675/20366138/085e92fc-ac07-11e6-951b-bee8d579a168.png)

**Comment by mzlock** [comment]
@lsweltz - assigned this to myself, although @brianjlandau might be able to get to it before I do.

**Comment by mzlock** [comment]
Fixed in master.

@brianjlandau - could you deploy this?

**Comment by lsweltz** [comment]
:+1:
