### ISSUE TITLE
Organization Form: Add Local/International Field

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/NGO-admin#8]
On the organization form:

- Add a required Local/International field. It should use a radio button field and include “international organization” and “local organization” as the options.

**Comment by mzlock** [comment]
@lsweltz - who should be able to see this radio button?  Admins only or can orgs self-categorize?

**Comment by mzlock** [comment]
We agreed that it should be accessible to everyone on the form.

@lsweltz - does this placement look alright?

![screen shot 2016-09-09 at 4 10 33 pm](https://cloud.githubusercontent.com/assets/1087001/18401395/4b9bf986-76a8-11e6-97dc-4b0a0ffbdd3e.png)
